var annotated_dup =
[
    [ "wex", null, [
      [ "plot", null, [
        [ "trace", "classwex_1_1plot_1_1trace.html", "classwex_1_1plot_1_1trace" ],
        [ "plot", "classwex_1_1plot_1_1plot.html", "classwex_1_1plot_1_1plot" ]
      ] ],
      [ "inputbox", "classwex_1_1inputbox.html", "classwex_1_1inputbox" ],
      [ "sMouse", "structwex_1_1s_mouse.html", "structwex_1_1s_mouse" ],
      [ "modalMgr", "classwex_1_1modal_mgr.html", "classwex_1_1modal_mgr" ],
      [ "eventhandler", "classwex_1_1eventhandler.html", "classwex_1_1eventhandler" ],
      [ "shapes", "classwex_1_1shapes.html", "classwex_1_1shapes" ],
      [ "gui", "classwex_1_1gui.html", "classwex_1_1gui" ],
      [ "panel", "classwex_1_1panel.html", "classwex_1_1panel" ],
      [ "drop", "classwex_1_1drop.html", "classwex_1_1drop" ],
      [ "groupbox", "classwex_1_1groupbox.html", "classwex_1_1groupbox" ],
      [ "layout", "classwex_1_1layout.html", "classwex_1_1layout" ],
      [ "button", "classwex_1_1button.html", "classwex_1_1button" ],
      [ "radiobutton", "classwex_1_1radiobutton.html", "classwex_1_1radiobutton" ],
      [ "checkbox", "classwex_1_1checkbox.html", "classwex_1_1checkbox" ],
      [ "msgbox", "classwex_1_1msgbox.html", "classwex_1_1msgbox" ],
      [ "label", "classwex_1_1label.html", "classwex_1_1label" ],
      [ "editbox", "classwex_1_1editbox.html", "classwex_1_1editbox" ],
      [ "multiline", "classwex_1_1multiline.html", "classwex_1_1multiline" ],
      [ "choice", "classwex_1_1choice.html", "classwex_1_1choice" ],
      [ "list", "classwex_1_1list.html", "classwex_1_1list" ],
      [ "windex", "classwex_1_1windex.html", "classwex_1_1windex" ],
      [ "menu", "classwex_1_1menu.html", "classwex_1_1menu" ],
      [ "menubar", "classwex_1_1menubar.html", "classwex_1_1menubar" ],
      [ "timer", "classwex_1_1timer.html", "classwex_1_1timer" ],
      [ "maker", "classwex_1_1maker.html", null ],
      [ "tabbed", "classwex_1_1tabbed.html", "classwex_1_1tabbed" ],
      [ "radiobuttonLayout", "classwex_1_1radiobutton_layout.html", "classwex_1_1radiobutton_layout" ],
      [ "printDoc", "classwex_1_1print_doc.html", "classwex_1_1print_doc" ],
      [ "free", "structwex_1_1free.html", null ],
      [ "property", "classwex_1_1property.html", "classwex_1_1property" ],
      [ "propertyGrid", "classwex_1_1property_grid.html", "classwex_1_1property_grid" ],
      [ "window2file", "classwex_1_1window2file.html", "classwex_1_1window2file" ],
      [ "com", "classwex_1_1com.html", "classwex_1_1com" ],
      [ "tcp", "classwex_1_1tcp.html", "classwex_1_1tcp" ],
      [ "filebox", "classwex_1_1filebox.html", "classwex_1_1filebox" ],
      [ "gauge", "classwex_1_1gauge.html", "classwex_1_1gauge" ],
      [ "slider", "classwex_1_1slider.html", "classwex_1_1slider" ],
      [ "slider2", "classwex_1_1slider2.html", "classwex_1_1slider2" ]
    ] ]
];